### PR TITLE
#14 #15 #16 footer component, Title Component and Navigation Component

### PR DESCRIPTION
**Pull request by adh86**
#14 #15 #16

### CODE REVIEW

**Review by bytewiz — CHANGES_REQUESTED** [review]
Can you please not `fork` the repo and just clone and create a branch for the repo?

This will save you a lot of headaches. will review it ones that is done also please name you branch something descriptive + prefix it with `feature/` for example `feature/header-component`

**Review by zkwsk — COMMENTED** [review]
Agree with @bytewiz. Additionally, you are making one PR for 3 issues. I would prefer to see one PR per issue. In this case it is not really a problem, but it could easily be in other cases. Imagine that you are building a navigation bar, but then you choose to add another issue that changes how the database work. We ten find out that the DB change needs to happen after something else has been done and suddenly we cannot merge the navigation bar even though it is finished.

If you had navigation bar in one story and menu items for that navigation bar in another, I would probably do both issues in the same PR because they are so closely interconnected, but otherwise not.

**Comment by laila1222** [comment]
I could not pull your branch from adh86:develop. I am guessing this is something to do with your repo being forked?

**Comment by adh86** [comment]
> I could not pull your branch from adh86:develop. I am guessing this is something to do with your repo being forked?

ok it was fork and I fixed

**Comment by bytewiz** [comment]
@adh86 This is still a fork, can you change it? so close this one and create a new one on a branch :v:

**Comment by bytewiz** [comment]
close in favor of new Pull Requests :v:

**Pull request closed without merging**
