### PR TITLE
Setting up prettier

### PR DESCRIPTION
**Pull request by zkwsk**
This PR will run Eslint and Prettier every time you commit.

Eslint will scan through your code and look for bad practices. Prettier will simply make sure that your code is always formatted nicely.

I also had to perform a lot of refactoring to the codebase because it was unfortunately not written with eslint running from the beginning.

Finally there is an editorconfig file added, which will help keep settings in your code editors the same. 

Unfortunately when you commit it seems that Prettier is currently running too late, so it runs right _after_ the commit instead of before. I don't understand why and I've opened an issue on the library I use to run things, but I don't have a solution yet. But now we have all of the configuration for eslint and prettier in the repo, so I recommend you all install the following extensions in Vscode (if you don't already have them):

- Eslint
- Prettier
- Editorconfig

Make sure to format code on save with prettier and you should be good. Be aware that you might have to change a lot of your code because of all of the new eslint rules. It is annoying, but it is for the better for everyone.

### CODE REVIEW

**Comment by zkwsk** [comment]
Not quite sure why the tests are failing on me. Looks like it can't resolve React from Jest?

**Comment by bytewiz** [comment]
@zkwsk seems to be some conflicts

**Review by bytewiz — CHANGES_REQUESTED** [review]
Looks fine, but need to resolve conflicts

**Review by bytewiz — APPROVED** [review]

**Review by mo3ni — APPROVED** [review]
😎

**Pull request merged**
