### PR TITLE
Feature/202/bug in annotation

### PR DESCRIPTION
**Pull request by aina21**
#202 
Screenshot_id and screenshot_key are saved to the localstorage on the home page.
Annotations are written to db, and are getting from db.

### CODE REVIEW

**Review by OlkaA — APPROVED** [review]
Great job!
Data is written to local storage and table annotations in database

**Comment by zkwsk** [comment]
I'm a little confused as to whether this one is ready for review? @OlkaA has approved it a while ago, but then there is a long list of commits since.

**Comment by OlkaA** [comment]
Screenshot_id and screenshot_key are saved to the localstorage on the home page.
Annotations are written to db, and are getting from db.

**Review by bytewiz — APPROVED** [review]
Seems right to me 👍

**Pull request merged**
