### PR TITLE
Issue #33 endpoint-create-annotation added #33

### PR DESCRIPTION
**Pull request by berheg**

### CODE REVIEW

**Comment by laila1222** [comment]
You have some conflicting files that need to be merged. Would you resolve the conflicts first? Then it is easier for us to review. :)

**Review by zkwsk — CHANGES_REQUESTED** [review]
Still conflicts.

**Comment by bytewiz** [comment]
@berheg this Pull request has a lot of unrelated changes. there should not be any changes done for the client-side for this Pull Request and also there is changes related to the screenshot backend task, that should be reverted as well.


> I think you have had branched out from a not up-to-date branch and if these changes are not removed from here we will start overwriting others work and we will lose a lot of time

**Review by laila1222 — CHANGES_REQUESTED** [review]
Following Niels latest review, when I go for "Files changed" I can still see many changes from the client side. Like for example: button, commentblogcard, etc. 
These shouldn't be in this issue, but only the files that are related to endpoint creation. 

What I would do is the following: 
- creating a new branch from develop. 
- copy paste the files from this branch into that new one, but only the ones that are RELATED TO ENDPOINT CREATION
- Push changes from this new branch. (and/or create new pr and close this - but not exactly sure about this step)
But of course this is just one way of fixing it. I just had the same problem today, and I did these steps, and it worked. Let me know if I can help. :)

**Comment by bytewiz** [comment]
@berheg please resolve the comments so we can continue

**Comment by bytewiz** [comment]
Closing this in favour of #104

**Pull request closed without merging**
