### PR TITLE
feature/99/propTypes

### PR DESCRIPTION
**Pull request by azinkamran**

### CODE REVIEW

**Comment by zkwsk** [comment]
Hey @azinkamran. I've not checked your code out yet, but something that comes to mind when I see this PR is that there is a number of commits from @bytewiz, @OlkaA and @Laila1222.

They could have been doing some work directly on your branch, but it looks more like you might have gotten something wrong merged into your branch or you may have branched out from a wrong place?

Can you have a look at those commits above (which are not yours) and confirm that the work is relevant to your PR?

**Comment by zkwsk** [comment]
Actully I don't even see any of your commits above 🙈 I'm pretty certain there is something wrong 😢

**Comment by bytewiz** [comment]
Yes @azinkamran Make sure your branch is up to date with the latest `develop` branch

**Comment by azinkamran** [comment]
> Actully I don't even see any of your commits above 🙈 I'm pretty certain there is something wrong 😢

I can see all the commits that I did in my branch, but when I send a pull request, it is not there.when I try to switch to origin, it shows all 22 files that I changed and this message: "Your branch is behind 'origin/develop' by 99 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)"

**Pull request closed without merging**
