### PR TITLE
Feature/32/screenshot

### PR DESCRIPTION
**Pull request by Fatemeh-Pakpour**
#32

### CODE REVIEW

**Review by bytewiz — CHANGES_REQUESTED** [review]
The database insertion looks good. We are missing the part where we call the API we are provided in #32 so in the controller, we should call his API and if we get a successful response we should get that result and insert it in the database :) we should get back a `url` and a `key` from the API call which we should store in the database

**Review by laila1222 — COMMENTED** [review]
If you rename your screenshot files (controller and router) into screenshots, it will follow the pattern that already exist for users and modules.

**Comment by OlkaA** [comment]
Nice work with swagger! Successfully added screenshots to DB using the updated Swagger.

**Comment by zkwsk** [comment]
It's not obvious to me whether @bytewiz comment is addressed. Further, there are some merge conflicts that needs to be resolved.

**Comment by Fatemeh-Pakpour** [comment]
@zkwsk , Thank you for your review, We fixed the conflicts.

**Comment by aina21** [comment]
@bytewiz Thank you for your review, we fix problem :)

**Comment by aina21** [comment]
@Laila1222 Thanks Laila :) we fixed it

**Review by bytewiz — APPROVED** [review]
Looks good to me 👍

**Review by laila1222 — APPROVED** [review]
Looks good, ready to merge! 👍

**Pull request merged**
