### PR TITLE
Issue#28 Storybook added new component UrlInput

### PR DESCRIPTION
**Pull request by OlkaA**
Added new component UrlInput 

#28

### CODE REVIEW

**Review by bytewiz — CHANGES_REQUESTED** [review]
Looks good, one comment to the `onKeyPress` handler

**Review by zkwsk — APPROVED** [review]
Looks great 👍 Good work :)

**Review by laila1222 — APPROVED** [review]
Looks good, tests are also passed 👍

**Review by bytewiz — APPROVED** [review]
💥 Looks good!

**Pull request merged**
